# from https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v2.yml
version: "2"
services:
  chrome:
    image: selenium/node-chrome:4.27.0-20241204
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    ports:
      - 6900:5900
#    networks:
#      - grid
 
  chrome_video:
    image: selenium/video:ffmpeg-7.1-20241204
    volumes:
      - ./videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - FILE_NAME=chrome_video.mp4
#      - SE_VIDEO_FILE_NAME=auto     
                  
  selenium-hub:
    image: selenium/hub:4.27.0-20241204
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
#    networks:
#      - grid
      
#networks:
#    grid:
 #    driver: bridge
